---
- name: Write a simple file # Label for the play (shows up on your terminal when you run the code so you know what ansible is working on)
  hosts: LL-rocky9-01 # Tells ansible where to run the commands. Must be defined in Invetory File! Can also set as localhost (run against itself)
  gather_facts: false # Ansible will spend a few seconds to learn about the target (IP addr, OS version, RAM, etc.) Setting to false makes the playbook start instantly
  tasks: # Marks the start of the actual work. A playbook can have many tasks; they run one after another from top to bottom.
    - name: Write file test.txt to temp directory # Another label explaining what this task does.
      ansible.builtin.lineinfile: # builtin Ansible module to manage text inside files
        path: /tmp/test.txt # Args: tells ansible where the file is or where it should be
        line: just a quick and simple test # Args: what we are writting in the text file
        create: true # Args: Create the file if it does not exist

# RUN: ansible-playbook -i inventory.yml write-file.yml