---
- name: A simple playbook to add users to a Rocky host
  hosts: web_servers
  gather_facts: false
  vars:
    ignore_users:
      - root
      - test1
    new_user:
      - test1
      - test2
      - test3
  
  tasks:
    - name: Add users to the Rocky host
      when: item not in ignore_users | default(omit)
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      become: true
      loop: "{{ new_user }}"

# ansible-playbook -i inventory.ini user.yml -e "{'new_user':['test1', 'test2']}" --ask-become-pass
# ansible-playbook -i inventory.ini user.yml --ask-become-pass